[default]
src = "src"
test = "test"
script = "script"

# Puedes definir endpoints RPC
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
testnet = "${TESTNET_RPC_URL}"

# Opciones de cobertura de tests
coverage = true
